// <auto-generated />
namespace BNE.PessoaJuridica.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class endereco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(endereco));
        
        string IMigrationMetadata.Id
        {
            get { return "201606242050427_endereco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
