// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BNE.PessoaFisica.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CandidaturaDegustacao
    {
        /// <summary>
        /// Initializes a new instance of the CandidaturaDegustacao class.
        /// </summary>
        public CandidaturaDegustacao()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CandidaturaDegustacao class.
        /// </summary>
        public CandidaturaDegustacao(int? quantidadeCandidatura = default(int?), bool? curriculoVIP = default(bool?), string uRL = default(string))
        {
            QuantidadeCandidatura = quantidadeCandidatura;
            CurriculoVIP = curriculoVIP;
            URL = uRL;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "QuantidadeCandidatura")]
        public int? QuantidadeCandidatura { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CurriculoVIP")]
        public bool? CurriculoVIP { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "URL")]
        public string URL { get; set; }

    }
}
