// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BNE.PessoaFisica.API.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CandidaturaResponse
    {
        /// <summary>
        /// Initializes a new instance of the CandidaturaResponse class.
        /// </summary>
        public CandidaturaResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CandidaturaResponse class.
        /// </summary>
        public CandidaturaResponse(decimal cPF, System.DateTime dataNascimento, string nome, bool candidatou, bool usuarioInvalido, string url = default(string))
        {
            CPF = cPF;
            DataNascimento = dataNascimento;
            Url = url;
            Nome = nome;
            Candidatou = candidatou;
            UsuarioInvalido = usuarioInvalido;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CPF")]
        public decimal CPF { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DataNascimento")]
        public System.DateTime DataNascimento { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Nome")]
        public string Nome { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Candidatou")]
        public bool Candidatou { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UsuarioInvalido")]
        public bool UsuarioInvalido { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Nome == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Nome");
            }
        }
    }
}
