// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BNE.PessoaFisica.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetByIdVagaCommand
    {
        /// <summary>
        /// Initializes a new instance of the GetByIdVagaCommand class.
        /// </summary>
        public GetByIdVagaCommand()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetByIdVagaCommand class.
        /// </summary>
        public GetByIdVagaCommand(int? idVaga = default(int?))
        {
            IdVaga = idVaga;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IdVaga")]
        public int? IdVaga { get; set; }

    }
}
