// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BNE.PessoaFisica.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GetCursoCommand
    {
        /// <summary>
        /// Initializes a new instance of the GetCursoCommand class.
        /// </summary>
        public GetCursoCommand()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetCursoCommand class.
        /// </summary>
        public GetCursoCommand(string query = default(string), int? limit = default(int?))
        {
            Query = query;
            Limit = limit;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Query")]
        public string Query { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Limit")]
        public int? Limit { get; set; }

    }
}
