// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BNE.PessoaFisica.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RecuperarCandidaturaDegustacaoCommand
    {
        /// <summary>
        /// Initializes a new instance of the
        /// RecuperarCandidaturaDegustacaoCommand class.
        /// </summary>
        public RecuperarCandidaturaDegustacaoCommand()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// RecuperarCandidaturaDegustacaoCommand class.
        /// </summary>
        public RecuperarCandidaturaDegustacaoCommand(decimal? cPF = default(decimal?), System.DateTime? data = default(System.DateTime?))
        {
            CPF = cPF;
            Data = data;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CPF")]
        public decimal? CPF { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public System.DateTime? Data { get; set; }

    }
}
