// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BNE.PessoaFisica.API.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RecuperarInformacaoCurriculoCommand
    {
        /// <summary>
        /// Initializes a new instance of the
        /// RecuperarInformacaoCurriculoCommand class.
        /// </summary>
        public RecuperarInformacaoCurriculoCommand()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// RecuperarInformacaoCurriculoCommand class.
        /// </summary>
        public RecuperarInformacaoCurriculoCommand(decimal? cPF = default(decimal?), int? idVaga = default(int?))
        {
            CPF = cPF;
            IdVaga = idVaga;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CPF")]
        public decimal? CPF { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IdVaga")]
        public int? IdVaga { get; set; }

    }
}
