// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BNE.WebServices.API.Client.Models
{
    using System.Linq;

    public partial class FacetField
    {
        /// <summary>
        /// Initializes a new instance of the FacetField class.
        /// </summary>
        public FacetField() { }

        /// <summary>
        /// Initializes a new instance of the FacetField class.
        /// </summary>
        /// <param name="fieldName">Campo solicitado para sumarização.
        /// Possible values include: 'SiglaEstado', 'NomeCidade',
        /// 'NomeEmpresa', 'Area', 'Escolaridade', 'Curso', 'Deficiencia',
        /// 'Funcao', 'TipoVinculo'</param>
        /// <param name="facets">Lista de valores e quantidades de
        /// ocorrência</param>
        public FacetField(string fieldName = default(string), System.Collections.Generic.IList<Facet> facets = default(System.Collections.Generic.IList<Facet>))
        {
            FieldName = fieldName;
            Facets = facets;
        }

        /// <summary>
        /// Gets or sets campo solicitado para sumarização. Possible values
        /// include: 'SiglaEstado', 'NomeCidade', 'NomeEmpresa', 'Area',
        /// 'Escolaridade', 'Curso', 'Deficiencia', 'Funcao', 'TipoVinculo'
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "FieldName")]
        public string FieldName { get; set; }

        /// <summary>
        /// Gets or sets lista de valores e quantidades de ocorrência
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Facets")]
        public System.Collections.Generic.IList<Facet> Facets { get; set; }

    }
}
