// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BNE.WebServices.API.Client.Models
{
    using System.Linq;

    /// <summary>
    /// Classe que representa uma resposta fornecida pelo candidato
    /// </summary>
    public partial class RespostaPergunta
    {
        /// <summary>
        /// Initializes a new instance of the RespostaPergunta class.
        /// </summary>
        public RespostaPergunta() { }

        /// <summary>
        /// Initializes a new instance of the RespostaPergunta class.
        /// </summary>
        /// <param name="idPergunta">Identificador da pergunta</param>
        /// <param name="resposta">Resposta fornecida pelo candidato</param>
        public RespostaPergunta(int? idPergunta = default(int?), bool? resposta = default(bool?))
        {
            IdPergunta = idPergunta;
            Resposta = resposta;
        }

        /// <summary>
        /// Gets or sets identificador da pergunta
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "IdPergunta")]
        public int? IdPergunta { get; set; }

        /// <summary>
        /// Gets or sets resposta fornecida pelo candidato
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Resposta")]
        public bool? Resposta { get; set; }

    }
}
