// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BNE.WebServices.API.Client.Models
{
    using System.Linq;

    public partial class ResultadoCadastroCVDTO
    {
        /// <summary>
        /// Initializes a new instance of the ResultadoCadastroCVDTO class.
        /// </summary>
        public ResultadoCadastroCVDTO() { }

        /// <summary>
        /// Initializes a new instance of the ResultadoCadastroCVDTO class.
        /// </summary>
        public ResultadoCadastroCVDTO(int? codigoCurriculo = default(int?), string mensagem = default(string))
        {
            CodigoCurriculo = codigoCurriculo;
            Mensagem = mensagem;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "CodigoCurriculo")]
        public int? CodigoCurriculo { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Mensagem")]
        public string Mensagem { get; set; }

    }
}
