//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNE.Curriculo_Pdf
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_Cidade
    {
        public TAB_Cidade()
        {
            this.BNE_Curriculo = new HashSet<BNE_Curriculo>();
            this.BNE_Curriculo1 = new HashSet<BNE_Curriculo>();
        }
    
        public int Idf_Cidade { get; set; }
        public string Nme_Cidade { get; set; }
        public bool Flg_Inativo { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public string Sig_Estado { get; set; }
        public double Txa_ISS { get; set; }
        public Nullable<int> Idf_Tipo_Base { get; set; }
        public Nullable<decimal> Cod_Rais { get; set; }
    
        public virtual ICollection<BNE_Curriculo> BNE_Curriculo { get; set; }
        public virtual ICollection<BNE_Curriculo> BNE_Curriculo1 { get; set; }
    }
}
