//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNE.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PalavraChave {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PalavraChave() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BNE.Web.Resources.PalavraChave", typeof(PalavraChave).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agradecimentos, consegui emprego, consegui vagas, consegui candidatos.
        /// </summary>
        internal static string AGRADECIMENTOS {
            get {
                return ResourceManager.GetString("AGRADECIMENTOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vaga, vagas, anunciar, cadastrar, divulgar, publicar, promover.
        /// </summary>
        internal static string ANUNCIARVAGA {
            get {
                return ResourceManager.GetString("ANUNCIARVAGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cadastrar currículo, curriculo, cadastrar cv, modelo cv, curriculum vitae, meu currículo, enviar curriculo, fazer curriculo.
        /// </summary>
        internal static string CADASTROCURRICULOMINI {
            get {
                return ResourceManager.GetString("CADASTROCURRICULOMINI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cadastro de empresa, gratuito, grátis.
        /// </summary>
        internal static string CADASTROEMPRESADADOS {
            get {
                return ResourceManager.GetString("CADASTROEMPRESADADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contato, bne, fale conosco, contato bne, banco nacional de empregos, banco nacional de emprego, atendimento.
        /// </summary>
        internal static string CONTATOSITE {
            get {
                return ResourceManager.GetString("CONTATOSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empregos, vagas, vagas emprego, emprego, vaga, currículo, curriculum, site empregos, recursos humanos, rh, recrutamento e seleção.
        /// </summary>
        internal static string DEFAULT {
            get {
                return ResourceManager.GetString("DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atendimento, sugestão, elogio, presidente, consegui emprego.
        /// </summary>
        internal static string FALEPRESIDENTE {
            get {
                return ResourceManager.GetString("FALEPRESIDENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vagas, vaga emprego, emprego, sine, vaga, site de emprego, curriculo, curriculum, curriculum vitae, vip, quem me viu.
        /// </summary>
        internal static string LOGINCOMERCIALCANDIDATO {
            get {
                return ResourceManager.GetString("LOGINCOMERCIALCANDIDATO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pesquisa curriculo, convocação por SMS, pesquisa cv, cv, anunciar vagas, busca de cv, empresa, candidato, cdd.
        /// </summary>
        internal static string LOGINCOMERCIALEMPRESA {
            get {
                return ResourceManager.GetString("LOGINCOMERCIALEMPRESA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNE São Paulo, BNE Curitiba, BNE Fazenda Rio Grande, BNE São José dos Pinhais, BNE Londrina, BNE Rio de Janeiro, unidades, lojas, ache o BNE, onde estamos.
        /// </summary>
        internal static string ONDEESTAMOS {
            get {
                return ResourceManager.GetString("ONDEESTAMOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pesquisa de currículo, pesquisa curriculum, pesquisa cv, cv, lista de currículos, gestão de curriculo, busca de curriculo, achar curriculos.
        /// </summary>
        internal static string PESQUISACURRICULO {
            get {
                return ResourceManager.GetString("PESQUISACURRICULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salario, pesquisa salarial, salarial, pretensão, faixa salarial, remuneração, dinheiro, salario minimo, aumento.
        /// </summary>
        internal static string PESQUISASALARIAL {
            get {
                return ResourceManager.GetString("PESQUISASALARIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vagas, emprego, vagas de emprego, empregos, sine, bne.com.br, seleção, processo seletivo, candidatar, oportunidades, novo emprego.
        /// </summary>
        internal static string PESQUISAVAGA {
            get {
                return ResourceManager.GetString("PESQUISAVAGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pesquisa de vagas, pesquisa vagas, vagas, pesquisa avançada, vaga, emprego, classificado emprego, oportunidades, novo emprego.
        /// </summary>
        internal static string PESQUISAVAGAAVANCADA {
            get {
                return ResourceManager.GetString("PESQUISAVAGAAVANCADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to informações de empresas, quem me viu, revisão de currículo, modelo de currículo, vagas no celular, jornal de vagas.
        /// </summary>
        internal static string PRODUTOVIP {
            get {
                return ResourceManager.GetString("PRODUTOVIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serviço, Recrutamento, ReS, seleção,  selecionar, Contratação, vagas, emprego, candidatos, entrevista, curriculum..
        /// </summary>
        internal static string R1DETALHES {
            get {
                return ResourceManager.GetString("R1DETALHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recrutamento, Recrutar, seleção, seletivo, contratar, candidato, currículo, vaga, recrutadores, recrutador, entrevista, Agência de emprego, recrutamento e Seleção.
        /// </summary>
        internal static string R1PRODUTO_R1_RECRUTAMENTO {
            get {
                return ResourceManager.GetString("R1PRODUTO_R1_RECRUTAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recrutamento, seleção, consultoria de Recursos Humanos, RH, recrutamento de seleção, Agência de emprego, candidatos, rápido, candidatos, entrevistas, vagas.
        /// </summary>
        internal static string R1PRODUTO_RECRUTAMENTO_R1 {
            get {
                return ResourceManager.GetString("R1PRODUTO_RECRUTAMENTO_R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposta comercial, recrutamento, seleção, valor de recrutamento,  seleção, Contratação, vagas, profissional..
        /// </summary>
        internal static string R1PROPOSTACOMERCIAL {
            get {
                return ResourceManager.GetString("R1PROPOSTACOMERCIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currículos, candidatos, agência, Recrutamento, ReS, seleção, selecionar, Contratação, vagas, emprego, entrevista, rápido, urgente, Recrutamento RH..
        /// </summary>
        internal static string R1VALORES {
            get {
                return ResourceManager.GetString("R1VALORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cursos, qualificação profissional, aperfeiçoamento, ensino a distancia, cursos on-line.
        /// </summary>
        internal static string SALAVIPCURSOS {
            get {
                return ResourceManager.GetString("SALAVIPCURSOS", resourceCulture);
            }
        }
    }
}
