//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanHouse.Entities.SalarioBR
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_Resultado_Pesquisa_Salarial
    {
        public int Idf_Resultado_Pesquisa_Salarial { get; set; }
        public int Idf_Funcao { get; set; }
        public string Sig_Estado { get; set; }
        public string Xml_Resultado_Pesquisa { get; set; }
        public string Xml_Resultado_Metricas { get; set; }
        public string Idfs_Funcoes { get; set; }
        public string Xml_Resultado_Escolaridade { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public Nullable<int> Qtd_Total_Amostra { get; set; }
        public Nullable<int> Qtd_Curriculos { get; set; }
    }
}
