namespace BNE.BLL.Enumeradores
{
    public enum RouteCollection
    {
        Cursos = 1,
        CursosPorFuncao = 2,
        Curso = 3,
        VagasPorFuncao = 4,
        VagasPorCidade = 5,
        VagasPorFuncaoCidade = 6,
        Vaga = 7,
        CurriculosPorFuncao = 8,
        CurriculosPorCidade = 9,
        CurriculosPorFuncaoCidade = 10,
        Curriculo = 11,
        Agradecimentos = 12,
        AnunciarVaga = 13,
        CadastroCurriculoMini = 14,
        AtualizarDadosEmpresa = 15,
        FalePresidente = 16,
        LoginComercialCandidato = 17,
        LoginComercialEmpresa = 18,
        OndeEstamos = 19,
        PesquisaCurriculo = 20,
        PesquisaVaga = 21,
        PesquisaVagaAvancada = 22,
        ProdutoVIP = 23,
        CurriculoAntigo = 24,
        VagaAntigo = 25,
        STC = 26,
        ApresentarR1 = 27,
        SimularR1 = 28,
        SolicitarR1 = 29,
        DetalheR1 = 30,
        EmitirPropostaR1 = 31,
        ApresentarR1_2 = 32,
        AlertaVagas = 33,
        VisualizacaoCurriculo = 34,
        ProdutoCIA = 35,
        VagasPorEmpresa = 37,
        LogarAutomatico = 39,
        ImpressaoCurriculo = 40,
        EscolhaPlano = 43,
        PagamentoPlano = 44,
        ConfirmacaoPagamento = 45,
        PagamentoPlanoCIA = 46,
        ConfirmacaoPagamentoCIA = 47,
        VagasPorPalavraChave = 48,
        EscolhaPlanoCIA = 49,
        ConfirmacaoPagamentoIntermediadores = 50,
        VagasAnunciadas = 51,
        SalaSelecionador = 52,
        ConfiguracaoSTC = 53,
        PesquisaCurriculoAvancada = 54,
        ConfirmacaoEmail = 55,
        PesquisaCurriculosNaoVistosPorVaga = 56,
        VagasPorArea = 57,

        #region Busca de Vagas (landing pages)
        BuscaDeVagas = 58,
        BuscaDeVagasPorEstado = 59,
        BuscaDeVagasPorArea = 60,
        BuscaDeVagasPorCidade = 61,
        #endregion Busca de Vagas (landing pages)

        Vagas = 62,
        VIPPromocao = 64,
        ConfirmacaoPagamentoErro = 65,
        CampanhaRecrutamento = 66,
        CadastroEmpresaUsuario = 69,
        ProdutoCIAPlano = 70,
        SalaVIP= 71,
        QuemMeViuVip = 72,
        QuemMeViuSemPlano = 73,
        QuemMeViuNaoVisualizado = 74,
        EscolherEmpresa = 75,
        RelatorioSalarialVip = 76,
        RelatorioSalarialSemPlano = 77, 
        ProdutoVipPlano = 78,
        SalaVipMensagens = 79,
        SalaVipJaEnviei = 80,
        SalaVipJaEnvieiNaoCandidatura = 81,        
        SalaSelecionadorConfiguracoes = 82,
        SalaSelecionadorMensagens = 83,    
        CadastroCurriculoDados = 85,
        CadastroCurriculoFormacao = 86,
        CadastroCurriculoComplementar = 87,
        CadastroCurriculoRevisao = 88,
        BlackFriday = 93,
        Download = 94,
        AlertaCurriculos = 98,
        Empresa = 99,
        PagamentoCandidatura = 100,
        PesquisaCurriculoFiltro = 106,
        ExcluirCurriculo = 107


    }
}
