namespace BNE.BLL.Enumeradores
{
    public enum CartaEmail
    {
        ConteudoPadraoBNE = 0,
        AgradecimentoCandidatura = 1,
        BoasVindasSine = 2,
        CadastroCurriculo = 3,
        //ContasTwitter = 4 , /* Retirado a pedido do Tortato em 26/02 */
        AtualizarCurriculo = 5,
        CadastroVaga = 7,
        CartilhaVIP = 8,
        ConfirmacaoPagamentoCIA = 9,
        ConfirmacaoPagamentoVIP = 10,
        ConfirmacaoPublicacao = 11,
        EmpresaLiberada = 12,
        IndiqueBNE = 13,
        RenovacaoCIA = 14,
        RenovacaoVIP = 15,
        RastreadorCurriculoEncontrado = 17,
        CadastroCurriculoSTC = 18,
        FalePresidente = 19,
        FaleConosco = 20,
        AbandonoCompra = 21,
        VagaEmMassa = 22,
        PecaAjuda = 23,
        ForaFaixa = 24,
        LinkVisualizacaoCurriculo = 25,
        EmailParaFiliais = 27,
        AtualizarEmpresa = 29,
        CurriculoInativado = 30,
        TerminoVipAntes = 31,
        PacoteVisualizacaoAntes = 32,
        DesistenciaCadastroEmpresa = 33,
        CadastroCurriculoSTCPadrao = 34,
        ConteudoPadraoEmpresa = 35,
        DesistenciaCadastroCurriculo = 36,
        ConteudoPadraoVIPUniversitario = 37,
        CadastroCurriculoVIPUniversitarioPadrao = 38,
        EnvioR1ParaVagasPoucasCandidaturas = 39,
        SolicitacaoR1 = 40,
        ConteudoPadraoBNERodape = 41,
        CompartilhamentoVagaPorEmail = 42,
        ConteudoBoletoVencimento = 43,
        ConteudoWebEstagiosIntegracaoAnuncioVaga = 45,
        ConteudoWebEstagiosIntegracaoCadastroEmpresa = 46,
        SolicitarContatoR1 = 47,
        ConteudoWebEstagiosIntegracaoQueroContratar = 48,
        ConteudoWebEstagiosIntegracaoPesquisaPorEstagiario = 49,
        SolicitarContatoCIA = 50,
        /// <summary>
        /// Carta a ser enviada ao responsável no financeiro para o tratamento de disputas.
        /// </summary>
        PagSeguro_AvisoDeDisputa = 51,
        ValidacaoEmail = 52,
        VendaPlanoVendedorAbaixoMinimo = 53,
        MensagemEmailCvPerfilVaga = 54,
        AlertaEmailExperienciaProfissional = 55,
        AlertaEmailExperienciaProfissionalFraca = 56,
        CandidatosPlanoLiberadoEmailSMSVaga = 57,
        DadosCandidatosPlanoLiberadoEmailSMSVaga = 58,
        ConteudoEmailAvisoCvsNaoVistos = 59,        
        EnviarEmailAlertaMensalFilial = 60,
        BoletosParaPagamento = 61,
        MensagemCiaNF = 62,
        MensagemVipNF = 63,
        BloqueioNaoPagamentoCartaoDeCredito = 64,
        BoasVindasNovamente = 65
    }
}
