//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanHouse.Entities.BNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BNE_Funcao_Pretendida
    {
        public int Idf_Curriculo { get; set; }
        public int Idf_Funcao_Pretendida { get; set; }
        public Nullable<int> Idf_Funcao { get; set; }
        public int Qtd_Experiencia { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public string Des_Funcao_Pretendida { get; set; }
    
        public virtual BNE_Curriculo BNE_Curriculo { get; set; }
        public virtual TAB_Funcao TAB_Funcao { get; set; }
    }
}
