//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanHouse.Entities.BNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BNE_Vaga
    {
        public BNE_Vaga()
        {
            this.BNE_Vaga_Candidato = new HashSet<BNE_Vaga_Candidato>();
            this.BNE_Plano_Adquirido_Detalhes = new HashSet<BNE_Plano_Adquirido_Detalhes>();
        }
    
        public int Idf_Vaga { get; set; }
        public Nullable<int> Idf_Funcao { get; set; }
        public int Idf_Cidade { get; set; }
        public string Cod_Vaga { get; set; }
        public Nullable<decimal> Vlr_Salario_De { get; set; }
        public Nullable<System.DateTime> Dta_Abertura { get; set; }
        public Nullable<System.DateTime> Dta_Prazo { get; set; }
        public string Eml_Vaga { get; set; }
        public string Des_Requisito { get; set; }
        public Nullable<short> Qtd_Vaga { get; set; }
        public string Nme_Empresa { get; set; }
        public bool Flg_Vaga_Rapida { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public bool Flg_Inativo { get; set; }
        public Nullable<int> Idf_Filial { get; set; }
        public bool Flg_Confidencial { get; set; }
        public int Idf_Usuario_Filial_Perfil { get; set; }
        public Nullable<int> Idf_Escolaridade { get; set; }
        public Nullable<short> Num_Idade_Minima { get; set; }
        public Nullable<short> Num_Idade_Maxima { get; set; }
        public Nullable<int> Idf_Sexo { get; set; }
        public string Des_Beneficio { get; set; }
        public string Des_Atribuicoes { get; set; }
        public string Num_DDD { get; set; }
        public string Num_Telefone { get; set; }
        public Nullable<bool> Flg_Receber_Cada_CV { get; set; }
        public Nullable<bool> Flg_Receber_Todos_CV { get; set; }
        public string Des_Funcao { get; set; }
        public Nullable<bool> Flg_Auditada { get; set; }
        public bool Flg_BNE_Recomenda { get; set; }
        public bool Flg_Vaga_Arquivada { get; set; }
        public bool Flg_Vaga_Massa { get; set; }
        public int Idf_Origem { get; set; }
        public Nullable<bool> Flg_Liberada { get; set; }
        public Nullable<int> Idf_Deficiencia { get; set; }
        public Nullable<System.DateTime> Dta_Auditoria { get; set; }
        public Nullable<decimal> Vlr_Salario_Para { get; set; }
        public Nullable<bool> Flg_Deficiencia { get; set; }
        public bool Flg_Empresa_Em_Auditoria { get; set; }
    
        public virtual TAB_Deficiencia TAB_Deficiencia { get; set; }
        public virtual TAB_Cidade TAB_Cidade { get; set; }
        public virtual TAB_Escolaridade TAB_Escolaridade { get; set; }
        public virtual TAB_Filial TAB_Filial { get; set; }
        public virtual TAB_Funcao TAB_Funcao { get; set; }
        public virtual ICollection<BNE_Vaga_Candidato> BNE_Vaga_Candidato { get; set; }
        public virtual TAB_Usuario_Filial_Perfil TAB_Usuario_Filial_Perfil { get; set; }
        public virtual ICollection<BNE_Plano_Adquirido_Detalhes> BNE_Plano_Adquirido_Detalhes { get; set; }
    }
}
