//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanHouse.Entities.BNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BNE_Carta_SMS
    {
        public int Idf_Carta_SMS { get; set; }
        public string Nme_Carta_SMS { get; set; }
        public string Vlr_Carta_SMS { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
    }
}
