//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanHouse.Entities.BNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BNE_Experiencia_Profissional
    {
        public Nullable<int> Idf_Area_BNE { get; set; }
        public int Idf_Pessoa_Fisica { get; set; }
        public int Idf_Experiencia_Profissional { get; set; }
        public string Raz_Social { get; set; }
        public string Des_Funcao_Exercida { get; set; }
        public Nullable<int> Idf_Funcao { get; set; }
        public System.DateTime Dta_Admissao { get; set; }
        public Nullable<System.DateTime> Dta_Demissao { get; set; }
        public string Des_Atividade { get; set; }
        public bool Flg_Inativo { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public Nullable<bool> Flg_Importado { get; set; }
        public Nullable<decimal> Vlr_Salario { get; set; }
        public string Des_Navegador { get; set; }
    
        public virtual TAB_Funcao TAB_Funcao { get; set; }
        public virtual TAB_Pessoa_Fisica TAB_Pessoa_Fisica { get; set; }
        public virtual TAB_Area_BNE TAB_Area_BNE { get; set; }
    }
}
