//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanHouse.Entities.BNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_Parametro_Curriculo
    {
        public int Idf_Parametro { get; set; }
        public int Idf_Curriculo { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public string Vlr_Parametro { get; set; }
        public bool Flg_Inativo { get; set; }
    
        public virtual BNE_Curriculo BNE_Curriculo { get; set; }
        public virtual TAB_Parametro TAB_Parametro { get; set; }
    }
}
