//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanHouse.Entities.BNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_Area_BNE
    {
        public TAB_Area_BNE()
        {
            this.BNE_Experiencia_Profissional = new HashSet<BNE_Experiencia_Profissional>();
            this.TAB_Funcao = new HashSet<TAB_Funcao>();
        }
    
        public int Idf_Area_BNE { get; set; }
        public string Des_Area_BNE { get; set; }
        public string Des_Area_BNE_Pesquisa { get; set; }
        public bool Flg_Inativo { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
    
        public virtual ICollection<BNE_Experiencia_Profissional> BNE_Experiencia_Profissional { get; set; }
        public virtual ICollection<TAB_Funcao> TAB_Funcao { get; set; }
    }
}
