//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanHouse.Entities.BNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_Curso
    {
        public TAB_Curso()
        {
            this.BNE_Formacao = new HashSet<BNE_Formacao>();
        }
    
        public int Idf_Curso { get; set; }
        public string Des_Curso { get; set; }
        public bool Flg_Inativo { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public bool Flg_Auditado { get; set; }
        public bool Flg_MEC { get; set; }
        public int Idf_Nivel_Curso { get; set; }
        public string Cod_Curso { get; set; }
    
        public virtual ICollection<BNE_Formacao> BNE_Formacao { get; set; }
    }
}
