//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanHouse.Entities.BNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_Pessoa_Fisica_Foto
    {
        public int Idf_Pessoa_Fisica { get; set; }
        public int Idf_Pessoa_Fisica_Foto { get; set; }
        public byte[] Img_Pessoa { get; set; }
        public bool Flg_Inativo { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public System.DateTime Dta_Alteracao { get; set; }
    
        public virtual TAB_Pessoa_Fisica TAB_Pessoa_Fisica { get; set; }
    }
}
