//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanHouse.Entities.BNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_Filial
    {
        public TAB_Filial()
        {
            this.TAB_Origem_Filial = new HashSet<TAB_Origem_Filial>();
            this.LAN_Companhia = new HashSet<LAN_Companhia>();
            this.LAN_Oportunidade = new HashSet<LAN_Oportunidade>();
            this.TAB_Parametro_Filial = new HashSet<TAB_Parametro_Filial>();
            this.TAB_Filial_Logo = new HashSet<TAB_Filial_Logo>();
            this.BNE_Vaga = new HashSet<BNE_Vaga>();
            this.TAB_Usuario_Filial_Perfil = new HashSet<TAB_Usuario_Filial_Perfil>();
            this.BNE_Pagamento = new HashSet<BNE_Pagamento>();
            this.BNE_Plano_Adquirido = new HashSet<BNE_Plano_Adquirido>();
            this.BNE_Plano_Adquirido_Detalhes = new HashSet<BNE_Plano_Adquirido_Detalhes>();
            this.TAB_Filial_Observacao = new HashSet<TAB_Filial_Observacao>();
            this.BNE_Intencao_Filial = new HashSet<BNE_Intencao_Filial>();
        }
    
        public int Idf_Filial { get; set; }
        public bool Flg_Matriz { get; set; }
        public Nullable<decimal> Num_CNPJ { get; set; }
        public string Raz_Social { get; set; }
        public string Nme_Fantasia { get; set; }
        public Nullable<int> Idf_CNAE_Principal { get; set; }
        public Nullable<int> Idf_Natureza_Juridica { get; set; }
        public int Idf_Endereco { get; set; }
        public string End_Site { get; set; }
        public string Num_DDD_Comercial { get; set; }
        public string Num_Comercial { get; set; }
        public bool Flg_Inativo { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public System.DateTime Dta_Alteracao { get; set; }
        public System.Data.Entity.Spatial.DbGeography Des_Localizacao { get; set; }
        public int Qtd_Funcionarios { get; set; }
        public string Des_IP { get; set; }
        public bool Flg_Oferece_Cursos { get; set; }
        public int Idf_Situacao_Filial { get; set; }
        public string Des_Pagina_Facebook { get; set; }
        public Nullable<int> Qtd_Usuario_Adicional { get; set; }
        public Nullable<int> Idf_Tipo_Parceiro { get; set; }
        public string Num_Comercial2 { get; set; }
    
        public virtual ICollection<TAB_Origem_Filial> TAB_Origem_Filial { get; set; }
        public virtual TAB_Endereco TAB_Endereco { get; set; }
        public virtual ICollection<LAN_Companhia> LAN_Companhia { get; set; }
        public virtual ICollection<LAN_Oportunidade> LAN_Oportunidade { get; set; }
        public virtual ICollection<TAB_Parametro_Filial> TAB_Parametro_Filial { get; set; }
        public virtual ICollection<TAB_Filial_Logo> TAB_Filial_Logo { get; set; }
        public virtual ICollection<BNE_Vaga> BNE_Vaga { get; set; }
        public virtual ICollection<TAB_Usuario_Filial_Perfil> TAB_Usuario_Filial_Perfil { get; set; }
        public virtual ICollection<BNE_Pagamento> BNE_Pagamento { get; set; }
        public virtual ICollection<BNE_Plano_Adquirido> BNE_Plano_Adquirido { get; set; }
        public virtual ICollection<BNE_Plano_Adquirido_Detalhes> BNE_Plano_Adquirido_Detalhes { get; set; }
        public virtual ICollection<TAB_Filial_Observacao> TAB_Filial_Observacao { get; set; }
        public virtual ICollection<BNE_Intencao_Filial> BNE_Intencao_Filial { get; set; }
    }
}
