//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNE.Web.LanHouse.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAN_Perfil
    {
        public LAN_Perfil()
        {
            this.LAN_Administrador = new HashSet<LAN_Administrador>();
        }
    
        public byte Idf_Perfil { get; set; }
        public string Des_Perfil { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public bool Flg_Inativo { get; set; }
    
        public virtual ICollection<LAN_Administrador> LAN_Administrador { get; set; }
    }
}
