//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNE.Web.LanHouse.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAN_Oportunidade_Cidade
    {
        public int Idf_Cidade { get; set; }
        public int Idf_Filial { get; set; }
        public int Idf_Companhia { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public bool Flg_Inativo { get; set; }
    
        public virtual LAN_Oportunidade LAN_Oportunidade { get; set; }
        public virtual TAB_Cidade TAB_Cidade { get; set; }
    }
}
