//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNE.Web.LanHouse.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_Fonte
    {
        public TAB_Fonte()
        {
            this.BNE_Formacao = new HashSet<BNE_Formacao>();
        }
    
        public int Idf_Fonte { get; set; }
        public string Sig_Fonte { get; set; }
        public string Nme_Fonte { get; set; }
        public bool Flg_Auditada { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public bool Flg_MEC { get; set; }
        public decimal Num_cnpj { get; set; }
    
        public virtual ICollection<BNE_Formacao> BNE_Formacao { get; set; }
    }
}
