// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BNE.PessoaFisica.API
{
    using Models;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Curso.
    /// </summary>
    public static partial class CursoExtensions
    {
            /// <summary>
            /// Recupera as sugestões de email
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='query'>
            /// </param>
            /// <param name='limit'>
            /// </param>
            public static IList<CursoResponse> GetCursos(this ICurso operations, string query = default(string), int? limit = default(int?))
            {
                return operations.GetCursosAsync(query, limit).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Recupera as sugestões de email
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='query'>
            /// </param>
            /// <param name='limit'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<CursoResponse>> GetCursosAsync(this ICurso operations, string query = default(string), int? limit = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetCursosWithHttpMessagesAsync(query, limit, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
