// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace BNE.PessoaFisica.API
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Vaga.
    /// </summary>
    public static partial class VagaExtensions
    {
            /// <summary>
            /// Recupera uma vaga pelo ID
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='idVaga'>
            /// </param>
            public static VagaResponse Get(this IVaga operations, int? idVaga = default(int?))
            {
                return operations.GetAsync(idVaga).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Recupera uma vaga pelo ID
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='idVaga'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<VagaResponse> GetAsync(this IVaga operations, int? idVaga = default(int?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(idVaga, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
