//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanHouse.Entities.BNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class BNE_Plano_Quantidade
    {
        public int Idf_Plano_Quantidade { get; set; }
        public System.DateTime Dta_Inicio_Quantidade { get; set; }
        public System.DateTime Dta_Fim_Quantidade { get; set; }
        public int Qtd_SMS { get; set; }
        public int Qtd_Visualizacao { get; set; }
        public int Qtd_SMS_Utilizado { get; set; }
        public int Qtd_Visualizacao_Utilizado { get; set; }
        public Nullable<bool> Flg_Inativo { get; set; }
        public System.DateTime Dta_Cadastro { get; set; }
        public Nullable<System.DateTime> Dta_Alteracao { get; set; }
        public Nullable<int> Idf_Plano_Adquirido { get; set; }
    
        public virtual BNE_Plano_Adquirido BNE_Plano_Adquirido { get; set; }
    }
}
