//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanHouse.Entities.BNE
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAN_Fase_Cadastro
    {
        public LAN_Fase_Cadastro()
        {
            this.LAN_Oportunidade_Curriculo = new HashSet<LAN_Oportunidade_Curriculo>();
        }
    
        public byte Idf_Fase_Cadastro { get; set; }
        public string Des_Fase_Cadastro { get; set; }
        public string Dta_Cadastro { get; set; }
    
        public virtual ICollection<LAN_Oportunidade_Curriculo> LAN_Oportunidade_Curriculo { get; set; }
    }
}
