// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BNE.WebServices.API.Client.Models
{
    using System.Linq;

    public partial class ExportaCandidatoResult
    {
        /// <summary>
        /// Initializes a new instance of the ExportaCandidatoResult class.
        /// </summary>
        public ExportaCandidatoResult() { }

        /// <summary>
        /// Initializes a new instance of the ExportaCandidatoResult class.
        /// </summary>
        public ExportaCandidatoResult(string message = default(string), int? id = default(int?), bool? existePessoaFisica = default(bool?))
        {
            Message = message;
            Id = id;
            ExistePessoaFisica = existePessoaFisica;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "ExistePessoaFisica")]
        public bool? ExistePessoaFisica { get; set; }

    }
}
