// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BNE.WebServices.API.Client.Models
{
    using System.Linq;

    /// <summary>
    /// Classe com as informações das funcoes pretendidas pelo candidato
    /// </summary>
    public partial class FuncaoPretendida
    {
        /// <summary>
        /// Initializes a new instance of the FuncaoPretendida class.
        /// </summary>
        public FuncaoPretendida() { }

        /// <summary>
        /// Initializes a new instance of the FuncaoPretendida class.
        /// </summary>
        /// <param name="funcao">Função pretendida pelo candidato
        /// O valor informado deve estar presente na tabela Funcoes</param>
        /// <param name="mesesDeExperiencia">Meses de experiência do candidato
        /// atuando naquela função</param>
        public FuncaoPretendida(string funcao, int? mesesDeExperiencia = default(int?))
        {
            Funcao = funcao;
            MesesDeExperiencia = mesesDeExperiencia;
        }

        /// <summary>
        /// Gets or sets função pretendida pelo candidato
        /// O valor informado deve estar presente na tabela Funcoes
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Funcao")]
        public string Funcao { get; set; }

        /// <summary>
        /// Gets or sets meses de experiência do candidato atuando naquela
        /// função
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "MesesDeExperiencia")]
        public int? MesesDeExperiencia { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Funcao == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "Funcao");
            }
        }
    }
}
